import "./globals.css";
import Link from "next/link";


export const metadata = {
    title: "Web tutorial",
    description: "Generated by sangjinsu",
};

export default function RootLayout({children}) {
    return (
        <html>
        <body>
        <h1><Link href="/">WEB</Link></h1>
        <ol>
            <li><Link href="/read/1">html</Link></li>
            <li><Link href="/read/2">css</Link></li>
        </ol>
        {children}
        <ul>
            <li><Link href="/create">create</Link></li>
            <li><Link href="/update/id">update</Link></li>
            <li><button>delete</button></li>
        </ul>
        </body>
        </html>
    );
}
