import "./globals.css";
import Link from "next/link";
import "./globals.css"

export const metadata = {
    title: "Web tutorial",
    description: "Generated by sangjinsu",
};

export default async function RootLayout({children}) {

    const resp = await fetch("http://localhost:9999/topics")
    const topics = await resp.json();

    return (
        <html>
        <body>
        <h1><Link href="/">WEB</Link></h1>
        <ol>
            {topics.map(topic => {
                return <li key={topic.id}><Link href={`/read/${topic.id}`}>{topic.title}</Link></li>
            })}
        </ol>
        {children}
        <ul>
            <li><Link href="/create">create</Link></li>
            <li><Link href="/update/id">update</Link></li>
            <li>
                <button>delete</button>
            </li>
        </ul>
        </body>
        </html>
    );
}
